package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDBANK_CARD_ITEM".
 */
public class GDBankCardItem {

    private long userId;
    private int cardId;
    private String bankBranch;
    private String bankCode;
    private String bankName;
    private String name;
    private String bankImg;
    private String bankIcon;

    public GDBankCardItem() {
    }

    public GDBankCardItem(long userId, int cardId, String bankBranch, String bankCode, String bankName, String name, String bankImg, String bankIcon) {
        this.userId = userId;
        this.cardId = cardId;
        this.bankBranch = bankBranch;
        this.bankCode = bankCode;
        this.bankName = bankName;
        this.name = name;
        this.bankImg = bankImg;
        this.bankIcon = bankIcon;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getCardId() {
        return cardId;
    }

    public void setCardId(int cardId) {
        this.cardId = cardId;
    }

    public String getBankBranch() {
        return bankBranch;
    }

    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    public String getBankCode() {
        return bankCode;
    }

    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBankImg() {
        return bankImg;
    }

    public void setBankImg(String bankImg) {
        this.bankImg = bankImg;
    }

    public String getBankIcon() {
        return bankIcon;
    }

    public void setBankIcon(String bankIcon) {
        this.bankIcon = bankIcon;
    }

}
