package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDINDUSTRY".
 */
public class GDIndustry {

    public Long id;
    public String realValue;
    public String text;

    public GDIndustry() {
    }

    public GDIndustry(Long id) {
        this.id = id;
    }

    public GDIndustry(Long id, String realValue, String text) {
        this.id = id;
        this.realValue = realValue;
        this.text = text;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRealValue() {
        return realValue;
    }

    public void setRealValue(String realValue) {
        this.realValue = realValue;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
