package com.thinkeract.tka.data.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gDIndustryDaoConfig;
    private final DaoConfig gDPhaseDaoConfig;
    private final DaoConfig gDBankItemDaoConfig;
    private final DaoConfig gDBankCardItemDaoConfig;
    private final DaoConfig gDGagUserItemDaoConfig;
    private final DaoConfig gDHistoryRecordDaoConfig;

    private final GDIndustryDao gDIndustryDao;
    private final GDPhaseDao gDPhaseDao;
    private final GDBankItemDao gDBankItemDao;
    private final GDBankCardItemDao gDBankCardItemDao;
    private final GDGagUserItemDao gDGagUserItemDao;
    private final GDHistoryRecordDao gDHistoryRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gDIndustryDaoConfig = daoConfigMap.get(GDIndustryDao.class).clone();
        gDIndustryDaoConfig.initIdentityScope(type);

        gDPhaseDaoConfig = daoConfigMap.get(GDPhaseDao.class).clone();
        gDPhaseDaoConfig.initIdentityScope(type);

        gDBankItemDaoConfig = daoConfigMap.get(GDBankItemDao.class).clone();
        gDBankItemDaoConfig.initIdentityScope(type);

        gDBankCardItemDaoConfig = daoConfigMap.get(GDBankCardItemDao.class).clone();
        gDBankCardItemDaoConfig.initIdentityScope(type);

        gDGagUserItemDaoConfig = daoConfigMap.get(GDGagUserItemDao.class).clone();
        gDGagUserItemDaoConfig.initIdentityScope(type);

        gDHistoryRecordDaoConfig = daoConfigMap.get(GDHistoryRecordDao.class).clone();
        gDHistoryRecordDaoConfig.initIdentityScope(type);

        gDIndustryDao = new GDIndustryDao(gDIndustryDaoConfig, this);
        gDPhaseDao = new GDPhaseDao(gDPhaseDaoConfig, this);
        gDBankItemDao = new GDBankItemDao(gDBankItemDaoConfig, this);
        gDBankCardItemDao = new GDBankCardItemDao(gDBankCardItemDaoConfig, this);
        gDGagUserItemDao = new GDGagUserItemDao(gDGagUserItemDaoConfig, this);
        gDHistoryRecordDao = new GDHistoryRecordDao(gDHistoryRecordDaoConfig, this);

        registerDao(GDIndustry.class, gDIndustryDao);
        registerDao(GDPhase.class, gDPhaseDao);
        registerDao(GDBankItem.class, gDBankItemDao);
        registerDao(GDBankCardItem.class, gDBankCardItemDao);
        registerDao(GDGagUserItem.class, gDGagUserItemDao);
        registerDao(GDHistoryRecord.class, gDHistoryRecordDao);
    }
    
    public void clear() {
        gDIndustryDaoConfig.getIdentityScope().clear();
        gDPhaseDaoConfig.getIdentityScope().clear();
        gDBankItemDaoConfig.getIdentityScope().clear();
        gDBankCardItemDaoConfig.getIdentityScope().clear();
        gDGagUserItemDaoConfig.getIdentityScope().clear();
        gDHistoryRecordDaoConfig.getIdentityScope().clear();
    }

    public GDIndustryDao getGDIndustryDao() {
        return gDIndustryDao;
    }

    public GDPhaseDao getGDPhaseDao() {
        return gDPhaseDao;
    }

    public GDBankItemDao getGDBankItemDao() {
        return gDBankItemDao;
    }

    public GDBankCardItemDao getGDBankCardItemDao() {
        return gDBankCardItemDao;
    }

    public GDGagUserItemDao getGDGagUserItemDao() {
        return gDGagUserItemDao;
    }

    public GDHistoryRecordDao getGDHistoryRecordDao() {
        return gDHistoryRecordDao;
    }

}
