package com.thinkeract.tka.data.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gDGoodsItemDaoConfig;
    private final DaoConfig gDAddressDaoConfig;

    private final GDGoodsItemDao gDGoodsItemDao;
    private final GDAddressDao gDAddressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gDGoodsItemDaoConfig = daoConfigMap.get(GDGoodsItemDao.class).clone();
        gDGoodsItemDaoConfig.initIdentityScope(type);

        gDAddressDaoConfig = daoConfigMap.get(GDAddressDao.class).clone();
        gDAddressDaoConfig.initIdentityScope(type);

        gDGoodsItemDao = new GDGoodsItemDao(gDGoodsItemDaoConfig, this);
        gDAddressDao = new GDAddressDao(gDAddressDaoConfig, this);

        registerDao(GDGoodsItem.class, gDGoodsItemDao);
        registerDao(GDAddress.class, gDAddressDao);
    }
    
    public void clear() {
        gDGoodsItemDaoConfig.getIdentityScope().clear();
        gDAddressDaoConfig.getIdentityScope().clear();
    }

    public GDGoodsItemDao getGDGoodsItemDao() {
        return gDGoodsItemDao;
    }

    public GDAddressDao getGDAddressDao() {
        return gDAddressDao;
    }

}
