package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDADDRESS".
 */
public class GDAddress {

    private Long id;
    private int userId;
    private int addressId;
    private int status;
    private String userAddressId;
    private String phone;
    private String contact;
    private String province;
    private String city;
    private String address;

    public GDAddress() {
    }

    public GDAddress(Long id) {
        this.id = id;
    }

    public GDAddress(Long id, int userId, int addressId, int status, String userAddressId, String phone, String contact, String province, String city, String address) {
        this.id = id;
        this.userId = userId;
        this.addressId = addressId;
        this.status = status;
        this.userAddressId = userAddressId;
        this.phone = phone;
        this.contact = contact;
        this.province = province;
        this.city = city;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getAddressId() {
        return addressId;
    }

    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getUserAddressId() {
        return userAddressId;
    }

    public void setUserAddressId(String userAddressId) {
        this.userAddressId = userAddressId;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
