package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDGAG_USER_ITEM".
 */
public class GDGagUserItem {

    private Long id;
    private String userId;
    private String roomId;
    private boolean isGag;
    private String userName;
    private String avatar;

    public GDGagUserItem() {
    }

    public GDGagUserItem(Long id) {
        this.id = id;
    }

    public GDGagUserItem(Long id, String userId, String roomId, boolean isGag, String userName, String avatar) {
        this.id = id;
        this.userId = userId;
        this.roomId = roomId;
        this.isGag = isGag;
        this.userName = userName;
        this.avatar = avatar;
    }

    public GDGagUserItem(String userId, String roomId, boolean isGag, String userName, String avatar) {
        this.userId = userId;
        this.roomId = roomId;
        this.isGag = isGag;
        this.userName = userName;
        this.avatar = avatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getRoomId() {
        return roomId;
    }

    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    public boolean getIsGag() {
        return isGag;
    }

    public void setIsGag(boolean isGag) {
        this.isGag = isGag;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

}
