package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDGOODS_ITEM".
 */
public class GDGoodsItem {

    private Long id;
    private int userId;
    private int goodsId;
    private int goodsCount;
    private int inventory;
    private int originalCount;
    private int sid;
    private float price;
    private float freight;
    private String userGoodsId;
    private String name;
    private String goodsImg;
    private String spec;
    private boolean isCheck;

    public GDGoodsItem() {
    }

    public GDGoodsItem(Long id) {
        this.id = id;
    }

    public GDGoodsItem(Long id, int userId, int goodsId, int goodsCount, int inventory, int originalCount, int sid, float price, float freight, String userGoodsId, String name, String goodsImg, String spec, boolean isCheck) {
        this.id = id;
        this.userId = userId;
        this.goodsId = goodsId;
        this.goodsCount = goodsCount;
        this.inventory = inventory;
        this.originalCount = originalCount;
        this.sid = sid;
        this.price = price;
        this.freight = freight;
        this.userGoodsId = userGoodsId;
        this.name = name;
        this.goodsImg = goodsImg;
        this.spec = spec;
        this.isCheck = isCheck;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(int goodsId) {
        this.goodsId = goodsId;
    }

    public int getGoodsCount() {
        return goodsCount;
    }

    public void setGoodsCount(int goodsCount) {
        this.goodsCount = goodsCount;
    }

    public int getInventory() {
        return inventory;
    }

    public void setInventory(int inventory) {
        this.inventory = inventory;
    }

    public int getOriginalCount() {
        return originalCount;
    }

    public void setOriginalCount(int originalCount) {
        this.originalCount = originalCount;
    }

    public int getSid() {
        return sid;
    }

    public void setSid(int sid) {
        this.sid = sid;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public float getFreight() {
        return freight;
    }

    public void setFreight(float freight) {
        this.freight = freight;
    }

    public String getUserGoodsId() {
        return userGoodsId;
    }

    public void setUserGoodsId(String userGoodsId) {
        this.userGoodsId = userGoodsId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGoodsImg() {
        return goodsImg;
    }

    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    public String getSpec() {
        return spec;
    }

    public void setSpec(String spec) {
        this.spec = spec;
    }

    public boolean getIsCheck() {
        return isCheck;
    }

    public void setIsCheck(boolean isCheck) {
        this.isCheck = isCheck;
    }

}
