package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDBANK_ITEM".
 */
public class GDBankItem {

    private Long id;
    protected String bankName;

    public GDBankItem() {
    }

    public GDBankItem(Long id) {
        this.id = id;
    }

    public GDBankItem(Long id, String bankName) {
        this.id = id;
        this.bankName = bankName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

}
