package com.thinkeract.tka.data.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GDHISTORY_RECORD".
 */
public class GDHistoryRecord {

    private Long id;
    private String searchKey;
    private String searchType;

    public GDHistoryRecord() {
    }

    public GDHistoryRecord(Long id) {
        this.id = id;
    }

    public GDHistoryRecord(Long id, String searchKey, String searchType) {
        this.id = id;
        this.searchKey = searchKey;
        this.searchType = searchType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSearchKey() {
        return searchKey;
    }

    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey;
    }

    public String getSearchType() {
        return searchType;
    }

    public void setSearchType(String searchType) {
        this.searchType = searchType;
    }

}
